In [42]:
import numpy as np
import pandas as pd

In [43]:
restaurant_data = {
    "Table_No" : [1, 2, 3],
    "Bill_Amount" : [1250, 890, 2400],
    "Waiter_name" : ['Amit', 'Priya', 'Rahul']
}
df = pd.DataFrame(restaurant_data)
print(df)
print(type(df))
print(df['Bill_Amount'])
print(type(df['Bill_Amount']))

   Table_No  Bill_Amount Waiter_name
0         1         1250        Amit
1         2          890       Priya
2         3         2400       Rahul
<class 'pandas.DataFrame'>
0    1250
1     890
2    2400
Name: Bill_Amount, dtype: int64
<class 'pandas.Series'>

In [44]:
# pd.Series - creates Series (1D data with an index)
# total_bill = [4700, 6744, 760, 4583]
total_bill = df['Bill_Amount']
x = pd.Series(total_bill.values, index = ['mon', 'tue', 'wed'])
print(x)
print

mon    1250
tue     890
wed    2400
dtype: int64

In [45]:
print(df.values)
print(df.to_numpy())
print(type(df.values))

[[1 1250 'Amit']
 [2 890 'Priya']
 [3 2400 'Rahul']]
[[1 1250 'Amit']
 [2 890 'Priya']
 [3 2400 'Rahul']]
<class 'numpy.ndarray'>

In [46]:
df = pd.read_csv("../Data/tip.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [47]:
print(df.head(5))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [48]:
print(df.tail(5))

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [49]:
print(df.sample(5))

     total_bill   tip     sex smoker   day    time  size
172        7.25  5.15    Male    Yes   Sun  Dinner     2
162       16.21  2.00  Female     No   Sun  Dinner     3
109       14.31  4.00  Female    Yes   Sat  Dinner     2
121       13.42  1.68  Female     No  Thur   Lunch     2
10        10.27  1.71    Male     No   Sun  Dinner     2

In [50]:
print(df.shape)
print(df.size)
print(df.columns.tolist())

(244, 7)
1708
['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [51]:
# info() - dtypes and null counts in one shot
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [52]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [53]:
print(df["day"].value_counts())
print(type(df["day"].value_counts()))

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
<class 'pandas.Series'>

In [54]:
print(df['day'].unique())
print(type(df['day'].unique()))

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str
<class 'pandas.arrays.StringArray'>

In [55]:
print(df['day'].nunique())
print(type(df['day'].nunique()))

4
<class 'int'>

In [56]:
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [59]:
summary = df.groupby('day').agg(
    bill_count = ('total_bill', 'size'),
    avg_bill = ('total_bill', 'mean'),
    avg_tip = ('tip', 'mean')
).round(2)
summary.reset_index()
summary.to_csv('../Data/practice.csv')

In [60]:
df.groupby('day')['tip'].idxmax()

day
Fri      95
Sat     170
Sun     183
Thur    141
Name: tip, dtype: int64

In [61]:
df.groupby('day')['tip'].max()

day
Fri      4.73
Sat     10.00
Sun      6.50
Thur     6.70
Name: tip, dtype: float64